# Generated by Django 4.1.5 on 2023-01-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='autorias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='miembros',
            field=models.IntegerField(default=0),
        ),
    ]
