# Generated by Django 4.1.5 on 2023-01-16 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vhsApp', '0002_choice_autorias_choice_miembros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='autorias',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='membresia',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='miembros',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='video',
        ),
    ]
