# Generated by Django 4.1.5 on 2023-01-16 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vhsApp', '0003_remove_choice_autorias_remove_choice_membresia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opciones', models.CharField(max_length=200)),
                ('votos', models.IntegerField(default=0)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vhsApp.pregunta')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
