# Generated by Django 4.1.5 on 2023-01-17 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vhsApp', '0004_opcion_delete_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='autoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vhsApp.usuario'),
        ),
    ]
